M48
; DRILL file {KiCad 8.0.1} date 2024-04-11T23:32:51+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2024-04-11T23:32:51+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X89.5Y-103.5
X89.5Y-141.5
X108.5Y-59.0
X127.5Y-103.5
X127.5Y-141.5
M30
